"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.socialLogin = exports.url = void 0;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
exports.url = __importStar(require("./url"));
/**
 * @controller UserController.socialLogin
 * @path GET /user/oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function socialLogin(connection, socialLoginData) {
    return PlainFetcher_1.PlainFetcher.fetch(connection, {
        ...socialLogin.METADATA,
        path: socialLogin.path(socialLoginData),
    });
}
exports.socialLogin = socialLogin;
(function (socialLogin) {
    socialLogin.METADATA = {
        method: "GET",
        path: "/user/oauth",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    };
    socialLogin.path = (socialLoginData) => {
        const variables = socialLoginData;
        const search = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined)
                continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded = search.toString();
        return `/user/oauth${encoded.length ? `?${encoded}` : ""}`;
        ;
    };
})(socialLogin || (exports.socialLogin = socialLogin = {}));
