/**
 * @packageDocumentation
 * @module api.functional.api.mail
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export * as newsletter from "./newsletter";
export * as test from "./test";
