"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.localSignUp = void 0;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller UserController.localSignUp
 * @path POST /user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function localSignUp(connection, signUpData) {
    return PlainFetcher_1.PlainFetcher.fetch({
        ...connection,
        headers: {
            ...(connection.headers ?? {}),
            "Content-Type": "application/json",
        },
    }, {
        ...localSignUp.METADATA,
        path: localSignUp.path(),
    }, signUpData);
}
exports.localSignUp = localSignUp;
(function (localSignUp) {
    localSignUp.METADATA = {
        method: "POST",
        path: "/user",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    };
    localSignUp.path = () => {
        return `/user`;
    };
})(localSignUp || (exports.localSignUp = localSignUp = {}));
