"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sendNewsLetter = void 0;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller MailController.sendNewsLetter
 * @path POST /api/mail/newsletter
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function sendNewsLetter(connection, emailInfo) {
    return PlainFetcher_1.PlainFetcher.fetch({
        ...connection,
        headers: {
            ...(connection.headers ?? {}),
            "Content-Type": "application/json",
        },
    }, {
        ...sendNewsLetter.METADATA,
        path: sendNewsLetter.path(),
    }, emailInfo);
}
exports.sendNewsLetter = sendNewsLetter;
(function (sendNewsLetter) {
    sendNewsLetter.METADATA = {
        method: "POST",
        path: "/api/mail/newsletter",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    };
    sendNewsLetter.path = () => {
        return `/api/mail/newsletter`;
    };
})(sendNewsLetter || (exports.sendNewsLetter = sendNewsLetter = {}));
