import type { EMAIL_ALREADY_EXIST } from "./EMAIL_ALREADY_EXIST";
import type { EMAIL_NOT_EXIST } from "./EMAIL_NOT_EXIST";
import type { MOONJIN_EMAIL_ALREADY_EXIST } from "./MOONJIN_EMAIL_ALREADY_EXIST";
import type { NICKNAME_ALREADY_EXIST } from "./NICKNAME_ALREADY_EXIST";
import type { ResponseFormResponseMessage } from "./ResponseFormResponseMessage";
import type { SIGNUP_ERROR } from "./SIGNUP_ERROR";
import type { WRITER_SIGNUP_ERROR } from "./WRITER_SIGNUP_ERROR";
export type TryCatchResponseMessageEMAIL_ALREADY_EXISTNICKNAME_ALREADY_EXISTMOONJIN_EMAIL_ALREADY_EXISTSIGNUP_ERRORWRITER_SIGNUP_ERROREMAIL_NOT_EXIST = EMAIL_ALREADY_EXIST | NICKNAME_ALREADY_EXIST | MOONJIN_EMAIL_ALREADY_EXIST | SIGNUP_ERROR | WRITER_SIGNUP_ERROR | EMAIL_NOT_EXIST | ResponseFormResponseMessage;
