/**
 * @packageDocumentation
 * @module api.functional.user.oauth.url
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, Resolved } from "@nestia/fetcher";
import type { ISocialRedirect } from "../../../../structures/ISocialRedirect";
/**
 * @controller UserController.redirectToSocialPlatform
 * @path GET /user/oauth/url
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function redirectToSocialPlatform(connection: IConnection, inputData: redirectToSocialPlatform.Query): Promise<void>;
export declare namespace redirectToSocialPlatform {
    type Query = Resolved<ISocialRedirect>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/user/oauth/url";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: (inputData: redirectToSocialPlatform.Query) => string;
}
