"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.redirectToSocialPlatform = void 0;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller UserController.redirectToSocialPlatform
 * @path GET /user/oauth/url
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function redirectToSocialPlatform(connection, inputData) {
    return PlainFetcher_1.PlainFetcher.fetch(connection, {
        ...redirectToSocialPlatform.METADATA,
        path: redirectToSocialPlatform.path(inputData),
    });
}
exports.redirectToSocialPlatform = redirectToSocialPlatform;
(function (redirectToSocialPlatform) {
    redirectToSocialPlatform.METADATA = {
        method: "GET",
        path: "/user/oauth/url",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    };
    redirectToSocialPlatform.path = (inputData) => {
        const variables = inputData;
        const search = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined)
                continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded = search.toString();
        return `/user/oauth/url${encoded.length ? `?${encoded}` : ""}`;
        ;
    };
})(redirectToSocialPlatform || (exports.redirectToSocialPlatform = redirectToSocialPlatform = {}));
