/**
 * @packageDocumentation
 * @module api.functional.user.email
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export * as uniqueness from "./uniqueness";
export * as verification from "./verification";
