/**
 * @packageDocumentation
 * @module api.functional.user.email.verification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, Resolved } from "@nestia/fetcher";
import type { IEmailVerification } from "../../../../structures/IEmailVerification";
/**
 *
 * @Summary 인증 메일에서 링크를 눌렀을 때 일어나는 인증 과정
 * @param payload 이메일 인증 code가 담긴 객체
 * @returns 메일 인증 결과 페이지로 redirect
 *
 * @controller UserController.emailVerification
 * @path GET /user/email/verification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function emailVerification(connection: IConnection, payload: emailVerification.Query): Promise<void>;
export declare namespace emailVerification {
    type Query = Resolved<IEmailVerification>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/user/email/verification";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: (payload: emailVerification.Query) => string;
}
