/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, Primitive } from "@nestia/fetcher";
export * as user from "./user";
/**
 * @controller AppController.getHello
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getHello(connection: IConnection): Promise<getHello.Output>;
export declare namespace getHello {
    type Output = Primitive<string>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: () => string;
}
