/**
 * @packageDocumentation
 * @module api.functional.api.mail.test
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, Primitive } from "@nestia/fetcher";
/**
 * @controller MailController.mailTest
 * @path GET /api/mail/test
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function mailTest(connection: IConnection): Promise<mailTest.Output>;
export declare namespace mailTest {
    type Output = Primitive<string>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/api/mail/test";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: () => string;
}
