-- AlterTable
ALTER TABLE "Oauth" ALTER COLUMN "oauthId" SET DATA TYPE VARCHAR(64),
ALTER COLUMN "social" SET DATA TYPE VARCHAR(8);

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "category" SET DATA TYPE VARCHAR(16);

-- AlterTable
ALTER TABLE "Series" ALTER COLUMN "category" SET DATA TYPE VARCHAR(16);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "password" SET DATA TYPE VARCHAR(64);
